### ISSUE TITLE
Fail to  build with numpy 2.0

### ISSUE THREAD

**Issue by shinaoka** [tuwien-cms/xprec#17]
@mwallerb 
Can we fix it quickly?

<img width="1313" alt="image" src="https://github.com/tuwien-cms/xprec/assets/15949860/ca8bf8fa-c160-480e-a489-3e4f00452286">

**Comment by mwallerb** [comment]
Thanks for catching this, Hiroshi!

This is really bad ... they **completely** broke the way dtypes are created.

See [numpy user dtypes] for some examples, but there are no examples on how to do this in a 1.0 and 2.0 compatible way. The [migration guide] is also less than helpful. I am inclined to restrict numpy compatibility to < 2.0 for now. Maybe [Tensorflow] will figure this out, and we can crib their solution.

[numpy user dtypes]: https://github.com/numpy/numpy-user-dtypes
[migration guide]: https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#the-pyarray-descr-struct-has-been-changed
[Tensorflow]: https://github.com/tensorflow/tensorflow/issues/67291
